spring.application.name=NewProject

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/NewSpringBootDatabase
spring.datasource.username=postgres
spring.datasource.password=Ramya@213
spring.jpa.hibernate.ddl-auto=update

server.port=8090

#swagger url:- localhost:8090/swagger-ui.html