spring.application.name=NewProject

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/NewSpringBootDatabase
spring.datasource.username=postgres
spring.datasource.password=Ramya@213
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=update

server.port=8090
#mandatory to set hibernate dialect for docker

#swagger url:- localhost:8090/swagger-ui.html

#Uncomment below DB configurations to connect to your local DB through docker
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update

#docker commands:
#Build jar file: mvn clean package -DskipTests
#Build docker image: docker build -t dockerreponame/dockerimagename:version .
                #Ex: docker build -t docsteth/demodockerrepo/springbootrestapis:0.0.1 . 
#check docker image is created or not: docker images
#create docker container: docker run -d -phostport:containerport --name givecontainername -e (write env variables here to connect to DB) dockerimageId
                     #Ex: docker run -d -p8090:8090 --name springbootrestapis -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/NewSpringBootDatabase -e SPRING_DATASOURCE_USERNAME=postgres -e SPRING_DATASOURCE_PASSWORD=Ramya@213 9d0affbd7306
# where host.docker.internal means it will connect your local machine from inside Docker
#check list of containers running: docker ps
#check list of containers that are stopped & running: docker ps -a
